# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QueryGIS
                                 A QGIS plugin
 Contorl GIS with ChatGPT
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-07
        copyright            : (C) 2025 by 3DLabs, Juseong Lee
        email                : juseonglee99@3dlabs.co.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QueryGIS class from file QueryGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .query_gis import QueryGIS
    return QueryGIS(iface)
