# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dockwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName("DockWidget")
        DockWidget.resize(773, 800)
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.mainLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents)
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.mainLayout.setObjectName("mainLayout")
        self.apiLayout = QtWidgets.QHBoxLayout()
        self.apiLayout.setObjectName("apiLayout")
        self.label_2 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.apiLayout.addWidget(self.label_2)
        self.line_apikey = QtWidgets.QLineEdit(self.dockWidgetContents)
        self.line_apikey.setObjectName("line_apikey")
        self.apiLayout.addWidget(self.line_apikey)
        self.mainLayout.addLayout(self.apiLayout)
        self.queryLayout = QtWidgets.QVBoxLayout()
        self.queryLayout.setObjectName("queryLayout")
        self.label = QtWidgets.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.queryLayout.addWidget(self.label)
        self.text_query = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.text_query.setObjectName("text_query")
        self.queryLayout.addWidget(self.text_query)
        self.btn_ask = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_ask.setObjectName("btn_ask")
        self.queryLayout.addWidget(self.btn_ask)
        self.label_3 = QtWidgets.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.queryLayout.addWidget(self.label_3)
        self.text_response = QtWidgets.QTextEdit(self.dockWidgetContents)
        self.text_response.setObjectName("text_response")
        self.queryLayout.addWidget(self.text_response)
        self.btn_run = QtWidgets.QPushButton(self.dockWidgetContents)
        self.btn_run.setObjectName("btn_run")
        self.queryLayout.addWidget(self.btn_run)
        self.status_label = QtWidgets.QLabel(self.dockWidgetContents)
        self.status_label.setAlignment(QtCore.Qt.AlignCenter)
        self.status_label.setObjectName("status_label")
        self.queryLayout.addWidget(self.status_label)
        self.mainLayout.addLayout(self.queryLayout)
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        _translate = QtCore.QCoreApplication.translate
        DockWidget.setWindowTitle(_translate("DockWidget", "QueryGIS"))
        self.label_2.setText(_translate("DockWidget", "API KEY"))
        self.label.setText(_translate("DockWidget", "Query"))
        self.btn_ask.setText(_translate("DockWidget", "Ask"))
        self.label_3.setText(_translate("DockWidget", "Response"))
        self.btn_run.setText(_translate("DockWidget", "Run"))
        self.status_label.setText(_translate("DockWidget", "Status: Waiting for your next command."))
